name: app

type: 'php:8.4'

mounts:
  'web/uploads':
    source: local
    source_path: uploads

disk: 256

relationships:
    database: 'database:mysql'

hooks:
  build: |
    set -x -e

    curl -s https://get.symfony.com/cloud/configurator | bash

    symfony-build    

  deploy: |
    set -x -e

    symfony-deploy